export const disciplines = [
  'Bailarín',
  'Bailarina',
  'Danzante',
  'Coreógrafo',
  'Coreógrafa',
  'Actor',
  'Actriz',
  'Comediante',
  'Stand up',
  'Cineasta',
  'Payaso',
  'Payasa',
  'Clown',
  'Malabarista',
  'Pole dancer',
  'Trapecista',
  'Acróbata',
  'Músico',
  'Música',
  'Cantante',
  'Compositor',
  'Compistora',
  'Ejecutante',
  'DJ',
  'Musicólogo',
  'Musicóloga',
  'Director de orquesta',
  'Pianista',
  'Guitarrista',
  'Violinista',
  'Bajista',
  'Baterista',
  'Saxofonista',
  'Clarinetista',
  'Corista',
  'Bajo',
  'Barítono',
  'Tenor ',
  'Contratenor',
  'Contralto',
  'Mezzosoprano',
  'Soprano',
  'Director audiovisual',
  'Directora audiovisual',
  'Director teatral',
  'Directora teatral',
  'Productor',
  'Productora',
  'Gestor cultural',
  'Gestora cultural',
  'Escenógrafo',
  'Escenógrafa',
  'Vestuarista',
  'Diseñador',
  'Diseñadora',
  'Confeccionista',
  'Maquillador',
  'Maquilladora',
  'Caracterizador',
  'Caracterizadora',
  'Performer',
  'Dramaturgo',
  'Dramaturga',
  'Iluminador Técnico',
  'Iluminadora Técnico',
  'Investigador',
  'Investigadora',
  'Trabajador social ',
  'Trabajadora social ',
  'Trabajador comunitario',
  'Trabajadora comunitaria',
  'Docente',
];

export const keywords = [
  'Danza',
  'Coreografías',
  'Contemporánea',
  'Ritmos latinos',
  'Salsa',
  'Bachata',
  'Mambo',
  'Merengue',
  'Tango',
  'Urbano',
  'Dancehall',
  'Break dance',
  'Locking',
  'Popping',
  'New style',
  'House dance',
  'Wacking',
  'Ballet',
  'Flamenco',
  'Arabe',
  'Tap',
  'Folcklore',
  'Pole Dance',
  'Twerk',
  'Chair dance',
  'Lap dance',
  'Stand up comedy',
  'Teatro',
  'Teatro de Títeres ',
  'Teatro testimonial',
  'Teatro musical',
  'Danza-teatro',
  'Teatro cinematográfico',
  'Teatro Físico',
  'Pantomima',
  'Teatro dramático',
  'Teatro infantil ',
  'Teatro de comedia',
  'Teatro de inmersión',
  'Teatro absurdo',
  'Teatro pedagógico',
  'Teatro de tragedia',
  'Opera',
  'Cine',
  'Cine independiente',
  'Cortometrajes',
  'Televisión',
  'Comerciales',
  'Series',
  'Novelas',
  'Arte Circenses',
  'Acrobacias',
  'Telas',
  'Trapecio',
  'Aro',
  'Cuerda',
  'Malabarismo',
  'Música',
  'Canto',
  'Canto popular',
  'Canto lírico',
  'Canto coral',
  'Ejecución',
  'Interpretación',
  'Instrumentos de viento',
  'Clarinete	',
  'Flauta',
  'Saxofón	',
  'Contrafagot',
  'Oboe	',
  'Píccolo',
  'Tuba	',
  'Bandoneón',
  'Trombón	',
  'Trompa',
  'Acordeón	',
  'Trompeta',
  'Armónica	',
  'Órgano de tubos',
  'Corno inglés	',
  'Flauta traversa',
  'Fagot	Gaita',
  'Cornetín	',
  'Corneta',
  'Instrumentos de Cuerdas',
  'Violín	',
  'Mandolina',
  'Contrabajo	',
  'Steel guitar',
  'Viola	',
  'Guitarrón',
  'Violonchelo	',
  'Charango',
  'Piano	',
  'Banjo',
  'Clavicordio	',
  'Sitar',
  'Salterio	',
  'Cítara',
  'Cimbalón	',
  'Laúd',
  'Arpa	',
  'Bajo',
  'Guitarra	',
  'Bajo fretless',
  'Instrumentos de percusión',
  'Tambor',
  'Timbal',
  'Xilifono',
  'Campana',
  'Crótalos',
  'Celesta',
  'Cajón',
  'Triángulo',
  'Taiko',
  'Castañuelas',
  'Maracas',
  'Bombo',
  'Batería',
  'Gong',
  'Pandereta',
  'Bongó',
  'Matraca',
  'Cabasa',
  'Atabaque',
  'Marimba',
  'instrumentos Electrónicos',
  'Teclado eléctrico',
  'Guitarra electrica',
  'Bajo electrico',
  'Tornamesa',
  'Caja de ritmos',
  'Educación musical',
  'Musicología',
  'Dirección',
  'Composición',
  'Creación colectiva',
  'Producción',
  'Producción musical',
  'Producción ejecutiva',
  'Producción artística',
  'Producción general',
  'Audiencias',
  'Gestión Cultural',
  'Educación somática ',
  'Educación',
  'Docencia',
  'Escenografía',
  'Maquillaje ',
  'Caracterización',
  'Efectos especiales',
  'Performance',
  'Dramaturgia',
  'Iluminación',
  'Investigación',
  'Docencia en danza',
  'Docencia en teatro',
  'Docencia en música',
];

export const topics = [
  'Enfoque de género',
  'Lgtbiq+',
  'Discapacidad ',
  'Inclusión',
  'Arte y tecnología',
  'Duelo',
  'Sátira',
  'Política',
  'Medio ambiente',
  'Salud mental',
  'Futuristas',
  'Experiencias personales',
  'Andino',
  'Ritual',
  'Religioso',
  'Racial',
];
